/** Semantic error codes returned in API error responses. */
export const ErrorCode = {
  // Generic
  INTERNAL_ERROR: 'ERR_INTERNAL_SERVER_ERROR',
  NOT_FOUND: 'ERR_NOT_FOUND',
  VALIDATION_FAILED: 'ERR_VALIDATION_FAILED',
  BAD_REQUEST: 'ERR_BAD_REQUEST',
  TOO_MANY_REQUESTS: 'ERR_TOO_MANY_REQUESTS',

  // Authentication
  UNAUTHORIZED: 'ERR_NOT_AUTHENTICATED',
  INVALID_CREDENTIALS: 'ERR_INVALID_CREDENTIALS',
  NOT_AUTHENTICATED: 'ERR_NOT_AUTHENTICATED',
  TOKEN_EXPIRED: 'ERR_TOKEN_EXPIRED',
  TOKEN_INVALID: 'ERR_TOKEN_INVALID',
  TOKEN_REVOKED: 'ERR_TOKEN_REVOKED',
  TOKEN_REUSE: 'ERR_TOKEN_REUSE',
  REFRESH_TOKEN_MISSING: 'ERR_REFRESH_TOKEN_MISSING',
  ACCOUNT_DISABLED: 'ERR_ACCOUNT_DISABLED',

  // Authorization
  FORBIDDEN: 'ERR_FORBIDDEN',
  INSUFFICIENT_PERMISSIONS: 'ERR_INSUFFICIENT_PERMISSIONS',
  UNAUTHORIZED_ACCESS: 'ERR_UNAUTHORIZED_ACCESS',

  // User / Registration
  EMAIL_TAKEN: 'ERR_EMAIL_TAKEN',
  USER_NOT_FOUND: 'ERR_USER_NOT_FOUND',

  // Password Reset
  PASSWORD_RESET_INVALID: 'ERR_PASSWORD_RESET_INVALID',
  RESET_TOKEN_INVALID: 'ERR_RESET_TOKEN_INVALID',
  RESET_TOKEN_EXPIRED: 'ERR_RESET_TOKEN_EXPIRED',

  // Email Verification
  VERIFICATION_TOKEN_INVALID: 'ERR_VERIFICATION_TOKEN_INVALID',
  VERIFICATION_TOKEN_EXPIRED: 'ERR_VERIFICATION_TOKEN_EXPIRED',
  EMAIL_ALREADY_VERIFIED: 'ERR_EMAIL_ALREADY_VERIFIED',

  // Database
  DATABASE_ERROR: 'ERR_DATABASE',
  DB_CONNECTION_ERROR: 'ERR_DB_CONNECTION',
  DB_TRANSACTION_ERROR: 'ERR_DB_TRANSACTION',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
